<a href="https://colab.research.google.com/github/ogiogidayo/EXB3-B/blob/main/qlab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# kadai2a
import numpy as np
from sympy.physics.quantum.qubit import matrix_to_qubit

def Ry(theta):
    return np.array([[np.cos(theta / 2), -np.sin(theta / 2)], [np.sin(theta / 2), np.cos(theta / 2)]])

def Rz(theta):
    return np.array([[np.exp(-1j * theta / 2), 0], [0, np.exp(1j * theta / 2)]])

phi = np.array([[1], [0]])

U = Rz(0.123) @ Ry(2.123) @ Rz(0.456)
v = U @ phi

vv = matrix_to_qubit(v)
print(vv)

# simulation
probabilities = np.abs(v)**2
measurements = np.random.choice(2, 100, p=probabilities.flatten())
print(f"count 0: {np.sum(measurements == 0)}")
print(f"count 1: {np.sum(measurements == 1)}")


0.467273909317754*|0> - 0.139186104938131*I*|0> + 0.861013761558237*|1> - 0.144698390697306*I*|1>
count 0: 26
count 1: 74


In [2]:
# kadai2b
import numpy as np

H = np.array([[1, 1], [1, -1]]) / np.sqrt(2)
CNOT = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0]])

phi = np.array([1, 0, 0, 0])

H_I = np.kron(H, np.eye(2))
v = H_I @ phi

v_ = CNOT @ v

print(v_)


probabilities = np.abs(v_)**2
measurements = np.random.choice(4, 10, p=probabilities)
print(f"count 00: {np.sum(measurements == 0)}")
print(f"count 01: {np.sum(measurements == 1)}")
print(f"count 10: {np.sum(measurements == 2)}")
print(f"count 11: {np.sum(measurements == 3)}")

[0.70710678 0.         0.         0.70710678]
count 00: 5
count 01: 0
count 10: 0
count 11: 5


In [3]:
# kadai2c
import numpy as np

q_00 = np.array([1, 0, 0, 0])
q_01 = np.array([0, 1, 0, 0])
q_10 = np.array([0, 0, 1, 0])
q_11 = np.array([0, 0, 0, 1])
q = (q_00 + q_01 + q_10 + q_11) / 2

q_0 = np.array([1, 0])

Q = np.kron(q, q_0)


Toffoli = np.eye(8)
Toffoli[6, 6] = 0
Toffoli[7, 7] = 0
Toffoli[6, 7] = 1
Toffoli[7, 6] = 1

Q_T = Toffoli @ Q

print(Q_T)

probabilities = np.abs(Q_T)**2
print(probabilities)
p_0 = probabilities[0] + probabilities[2] + probabilities[4] + probabilities[6]
p_1 = probabilities[1] + probabilities[3] + probabilities[5] + probabilities[7]
measurements = np.random.choice([0, 1], 1000, p=[np.sum(p_0), np.sum(p_1)])

count_0 = np.sum(measurements == 0)
count_1 = np.sum(measurements == 1)

print(f"count 0: {count_0}")
print(f"count 1: {count_1}")

# 考察
# 2bitの0/1のANDは４つの組み合わせのうち11だけが1になる。つまり1になる確率が1/4で0になる確率が3/4であるため

[0.5 0.  0.5 0.  0.5 0.  0.  0.5]
[0.25 0.   0.25 0.   0.25 0.   0.   0.25]
count 0: 716
count 1: 284
